spring:
  application:
    name: user-mail-event-consumer
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by gradle when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
  profiles:
    active: local #spring.profiles.active#
server:
  port: ${PORT:8881}
---
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: user-events-listener-group
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: azamblackps606862@gmail.com
    password: pjgfsbppnjzavoiq
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 500
          starttls:
            enable: true

